"""to_numeric

Revision ID: 3b1234ee44f7
Revises: 3da05b628418
Create Date: 2025-02-20 18:23:43.158941

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3b1234ee44f7'
down_revision = '7ba1ae9aa530'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('campaigns', 'cost_per_impression',
               existing_type=sa.INTEGER(),
               type_=sa.NUMERIC(precision=20, scale=2),
               existing_nullable=False)
    op.alter_column('campaigns', 'cost_per_click',
               existing_type=sa.INTEGER(),
               type_=sa.NUMERIC(precision=20, scale=2),
               existing_nullable=False)
    op.alter_column('client_click_campaigns', 'cost',
               existing_type=sa.INTEGER(),
               type_=sa.NUMERIC(precision=20, scale=2),
               existing_nullable=False)
    op.alter_column('client_view_campaigns', 'cost',
               existing_type=sa.INTEGER(),
               type_=sa.NUMERIC(precision=20, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client_view_campaigns', 'cost',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('client_click_campaigns', 'cost',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('campaigns', 'cost_per_click',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('campaigns', 'cost_per_impression',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###