"""initial

Revision ID: 7ba1ae9aa530
Revises: 
Create Date: 2025-02-16 01:20:05.624679

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '7ba1ae9aa530'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advertisers',
    sa.Column('advertiser_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('advertiser_id')
    )
    op.create_table('clients',
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('login', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_table('campaigns',
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('advertiser_id', sa.Uuid(), nullable=False),
    sa.Column('impressions_limit', sa.Integer(), nullable=False),
    sa.Column('clicks_limit', sa.Integer(), nullable=False),
    sa.Column('cost_per_impression', sa.Integer(), nullable=False),
    sa.Column('cost_per_click', sa.Integer(), nullable=False),
    sa.Column('ad_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ad_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ad_image_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('start_date', sa.Integer(), nullable=False),
    sa.Column('end_date', sa.Integer(), nullable=False),
    sa.Column('target_gender', sa.String(), nullable=True),
    sa.Column('target_age_from', sa.Integer(), nullable=True),
    sa.Column('target_age_to', sa.Integer(), nullable=True),
    sa.Column('target_location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['advertiser_id'], ['advertisers.advertiser_id'], ),
    sa.PrimaryKeyConstraint('campaign_id')
    )
    op.create_table('client_advertiser_scores',
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('advertiser_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['advertiser_id'], ['advertisers.advertiser_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('client_id', 'advertiser_id')
    )
    op.create_table('client_click_campaigns',
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.campaign_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('client_id', 'campaign_id')
    )
    op.create_table('client_view_campaigns',
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.campaign_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('client_id', 'campaign_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_view_campaigns')
    op.drop_table('client_click_campaigns')
    op.drop_table('client_advertiser_scores')
    op.drop_table('campaigns')
    op.drop_table('clients')
    op.drop_table('advertisers')
    # ### end Alembic commands ###