"""indexes

Revision ID: 7f6cd23674c4
Revises: 3b1234ee44f7
Create Date: 2025-02-21 00:10:17.581336

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '7f6cd23674c4'
down_revision = '3b1234ee44f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_advertisers_advertiser_id'), 'advertisers', ['advertiser_id'], unique=False)
    op.create_index(op.f('ix_campaigns_advertiser_id'), 'campaigns', ['advertiser_id'], unique=False)
    op.create_index(op.f('ix_campaigns_campaign_id'), 'campaigns', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_client_advertiser_scores_advertiser_id'), 'client_advertiser_scores', ['advertiser_id'], unique=False)
    op.create_index(op.f('ix_client_advertiser_scores_client_id'), 'client_advertiser_scores', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_click_campaigns_campaign_id'), 'client_click_campaigns', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_client_click_campaigns_client_id'), 'client_click_campaigns', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_view_campaigns_campaign_id'), 'client_view_campaigns', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_client_view_campaigns_client_id'), 'client_view_campaigns', ['client_id'], unique=False)
    op.create_index(op.f('ix_clients_client_id'), 'clients', ['client_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clients_client_id'), table_name='clients')
    op.drop_index(op.f('ix_client_view_campaigns_client_id'), table_name='client_view_campaigns')
    op.drop_index(op.f('ix_client_view_campaigns_campaign_id'), table_name='client_view_campaigns')
    op.drop_index(op.f('ix_client_click_campaigns_client_id'), table_name='client_click_campaigns')
    op.drop_index(op.f('ix_client_click_campaigns_campaign_id'), table_name='client_click_campaigns')
    op.drop_index(op.f('ix_client_advertiser_scores_client_id'), table_name='client_advertiser_scores')
    op.drop_index(op.f('ix_client_advertiser_scores_advertiser_id'), table_name='client_advertiser_scores')
    op.drop_index(op.f('ix_campaigns_campaign_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_advertiser_id'), table_name='campaigns')
    op.drop_index(op.f('ix_advertisers_advertiser_id'), table_name='advertisers')
    # ### end Alembic commands ###