{
 "title": "Advertiser Statistic",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "advertiser",
    "label": "Advertiser",
    "query": "SELECT advertiser_id __value, name __text FROM advertisers"
   },
   {
    "name": "campaign",
    "label": "Campaign",
    "query": "SELECT campaign_id __value, ad_title __text FROM campaigns c WHERE c.advertiser_id = '$advertiser'"
   }
  ]
 },
 "panels": [
  {
   "title": "Статистика по рекламодателю",
   "type": "trend",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT date, COUNT(*) \"Показы\"\r\nFROM client_view_campaigns v\r\nJOIN campaigns c ON c.campaign_id = v.campaign_id\r\nWHERE c.advertiser_id = '$advertiser'\r\nGROUP BY date\r\nORDER BY date"
    },
    {
     "rawSql": "SELECT date, COUNT(*) \"Переходы\"\r\nFROM client_click_campaigns v\r\nJOIN campaigns c ON c.campaign_id = v.campaign_id\r\nWHERE c.advertiser_id = '$advertiser'\r\nGROUP BY date\r\nORDER BY date"
    }
   ]
  },
  {
   "title": "Соотношение показов",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT c.ad_title, COUNT(*)\r\nFROM client_view_campaigns v\r\nJOIN campaigns c ON c.campaign_id = v.campaign_id\r\nWHERE c.advertiser_id = '$advertiser'\r\nGROUP BY c.campaign_id"
    }
   ]
  },
  {
   "title": "Соотношение переходов",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT c.ad_title, COUNT(*)\r\nFROM client_click_campaigns v\r\nJOIN campaigns c ON c.campaign_id = v.campaign_id\r\nWHERE c.advertiser_id = '$advertiser'\r\nGROUP BY c.campaign_id"
    }
   ]
  },
  {
   "title": "Возраст перешедших",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT cl.age, COUNT(*)\r\nFROM client_click_campaigns v\r\nJOIN campaigns c ON c.campaign_id = v.campaign_id\r\nJOIN clients cl ON cl.client_id = v.client_id\r\nWHERE c.advertiser_id = '$advertiser'\r\nGROUP BY cl.age"
    }
   ]
  },
  {
   "title": "Показы/переходы кампании",
   "type": "trend",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT date, COUNT(*) \"Показы\"\r\nFROM client_view_campaigns v\r\nWHERE v.campaign_id = '$campaign'\r\nGROUP BY date\r\nORDER BY date"
    },
    {
     "rawSql": "SELECT date, COUNT(*) \"Переходы\"\r\nFROM client_click_campaigns v\r\nWHERE v.campaign_id = '$campaign'\r\nGROUP BY date\r\nORDER BY date"
    }
   ]
  },
  {
   "title": "Конверсия кампании",
   "type": "trend",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT date, (\r\n  SELECT COUNT(*) FROM client_click_campaigns cl\r\n  WHERE cl.campaign_id = '$campaign' AND cl.date = v.date\r\n) * 100 / COUNT(*) \"Конверсия\"\r\nFROM client_view_campaigns v\r\nWHERE v.campaign_id = '$campaign'\r\nGROUP BY date\r\nORDER BY date"
    }
   ]
  },
  {
   "title": "Траты на рекламу",
   "type": "trend",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT date, SUM(cost) \"Показы\"\r\nFROM client_view_campaigns v\r\nJOIN campaigns c ON c.campaign_id = v.campaign_id\r\nWHERE c.advertiser_id = '$advertiser'\r\nGROUP BY date\r\nORDER BY date"
    },
    {
     "rawSql": "SELECT date, SUM(cost) \"Переходы\"\r\nFROM client_click_campaigns v\r\nJOIN campaigns c ON c.campaign_id = v.campaign_id\r\nWHERE c.advertiser_id = '$advertiser'\r\nGROUP BY date\r\nORDER BY date"
    }
   ]
  }
 ]
}