{
 "title": "Statistic Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Заработок",
   "type": "trend",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT date, SUM(cost) \"Показы\"\r\nFROM client_view_campaigns v\r\nGROUP BY date\r\nORDER BY date"
    },
    {
     "rawSql": "SELECT date, SUM(cost) \"Переходы\"\r\nFROM client_click_campaigns v\r\nGROUP BY date\r\nORDER BY date"
    }
   ]
  },
  {
   "title": "Соотношение показов",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT a.name, COUNT(*)\r\nFROM client_view_campaigns v\r\nJOIN campaigns c ON c.campaign_id = v.campaign_id\r\nJOIN advertisers a ON a.advertiser_id = c.advertiser_id\r\nGROUP BY a.advertiser_id"
    }
   ]
  },
  {
   "title": "Соотношение переходов",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT a.name, COUNT(*)\r\nFROM client_click_campaigns v\r\nJOIN campaigns c ON c.campaign_id = v.campaign_id\r\nJOIN advertisers a ON a.advertiser_id = c.advertiser_id\r\nGROUP BY a.advertiser_id"
    }
   ]
  },
  {
   "title": "Конверсия",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT a.name, (\r\n  SELECT COUNT(*) FROM client_click_campaigns cl\r\n  JOIN campaigns c ON c.campaign_id = cl.campaign_id AND c.advertiser_id = a.advertiser_id\r\n)::float / (\r\n  SELECT COUNT(*) FROM client_view_campaigns v\r\n  JOIN campaigns c ON c.campaign_id = v.campaign_id AND c.advertiser_id = a.advertiser_id\r\n) * 100\r\nFROM advertisers a\r\nGROUP BY a.advertiser_id\r\n"
    }
   ]
  },
  {
   "title": "Соотношение прибыли",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT a.name, COALESCE(SUM(v.cost), 0) + COALESCE(SUM(cl.cost), 0)\r\nFROM campaigns c\r\nJOIN advertisers a ON a.advertiser_id = c.advertiser_id\r\nLEFT JOIN client_view_campaigns v ON c.campaign_id = v.campaign_id\r\nLEFT JOIN client_click_campaigns cl ON c.campaign_id = cl.campaign_id\r\nGROUP BY a.advertiser_id\r\n"
    }
   ]
  }
 ]
}