apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    url: db
    database: prod
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      sslmode: "disable"
    isDefault: true
    editable: true
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    jsonData:
      graphiteVersion: "1.1"
      tlsAuth: false
      tlsAuthWithCACert: false
    version: 1
    editable: true
